# Generated by Django 5.1.1 on 2025-09-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Support'), ('operations', 'Operations'), ('finance', 'Finance'), ('legal', 'Legal'), ('hr', 'HR'), ('technology', 'Technology'), ('itsecurity', 'IT & Security'), ('auditquality', 'Audit & Quality'), ('employeemanagement', 'Employee Management'), ('logistics', 'Operations Logistics'), ('analytics', 'Business Intelligence'), ('projectstasks', 'Projects & Tasks')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('support', 'Support'), ('operations', 'Operations'), ('finance', 'Finance'), ('legal', 'Legal'), ('hr', 'HR'), ('technology', 'Technology'), ('itsecurity', 'IT & Security'), ('auditquality', 'Audit & Quality'), ('employeemanagement', 'Employee Management'), ('logistics', 'Operations Logistics'), ('analytics', 'Business Intelligence'), ('projectstasks', 'Projects & Tasks')], default='sales', max_length=50),
        ),
    ]
